;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Simulation/AbilitySystem/GameplayTag/DT_SpecGameplayTags.DT_SpecGameplayTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Ability.AGV.State.PrepareItem",NewTagName="Ability.AGV.State.PrepareWork")
+GameplayTagRedirects=(OldTagName="State.DT.AGV.PrepareItem",NewTagName="State.DT.AGV.PrepareWork")
+GameplayTagRedirects=(OldTagName="DT.TargetPoint.Cell.Enter",NewTagName="DT.TargetPoint.Cell.Enterance")
+GameplayTagList=(Tag="Ability.AGV.State.AlignBase",DevComment="")
+GameplayTagList=(Tag="Ability.AGV.State.Idle",DevComment="")
+GameplayTagList=(Tag="Ability.AGV.State.MoveToCell",DevComment="")
+GameplayTagList=(Tag="Ability.AGV.State.PrepareWork",DevComment="")
+GameplayTagList=(Tag="Ability.AGV.State.ReturnToBase",DevComment="")
+GameplayTagList=(Tag="Ability.AGV.State.WaitCell",DevComment="")
+GameplayTagList=(Tag="DT.Asset.Cell.A",DevComment="")
+GameplayTagList=(Tag="DT.Asset.Cell.B",DevComment="")
+GameplayTagList=(Tag="DT.Asset.Cell.C",DevComment="")
+GameplayTagList=(Tag="DT.Asset.Spec.A",DevComment="")
+GameplayTagList=(Tag="DT.Asset.Spec.B",DevComment="")
+GameplayTagList=(Tag="DT.Asset.Spec.Test",DevComment="")
+GameplayTagList=(Tag="DT.TargetPoint.AGV.Base.1",DevComment="")
+GameplayTagList=(Tag="DT.TargetPoint.AGV.Base.2",DevComment="")
+GameplayTagList=(Tag="DT.TargetPoint.Cell.Enterance",DevComment="")
+GameplayTagList=(Tag="DT.Type.Cell",DevComment="")
+GameplayTagList=(Tag="DT.Type.Cell.A",DevComment="")
+GameplayTagList=(Tag="DT.Type.Cell.B",DevComment="")
+GameplayTagList=(Tag="DT.Type.Cell.C",DevComment="")
+GameplayTagList=(Tag="DT.Type.Robot",DevComment="")
+GameplayTagList=(Tag="DT.Type.Robot.AGV",DevComment="")
+GameplayTagList=(Tag="DT.Type.Robot.AMR",DevComment="")
+GameplayTagList=(Tag="DT.Type.Robot.Manipulator",DevComment="")
+GameplayTagList=(Tag="DT.Type.Robot.Welder",DevComment="")
+GameplayTagList=(Tag="Event.DT.Spec.Create",DevComment="")
+GameplayTagList=(Tag="Event.DT.Spec.Ready",DevComment="")
+GameplayTagList=(Tag="Event.Request.AGV.Spec",DevComment="")
+GameplayTagList=(Tag="Event.Response.AGV.Spec",DevComment="")
+GameplayTagList=(Tag="State.DT.AGV.AlignBase",DevComment="")
+GameplayTagList=(Tag="State.DT.AGV.Idle",DevComment="")
+GameplayTagList=(Tag="State.DT.AGV.MoveToCell",DevComment="")
+GameplayTagList=(Tag="State.DT.AGV.PrepareWork",DevComment="")
+GameplayTagList=(Tag="State.DT.AGV.ReturnToBase",DevComment="")
+GameplayTagList=(Tag="State.DT.AGV.WaitCell",DevComment="")

